struct Color
        r       GLfloat         ?
        g       GLfloat         ?
        b       GLfloat         ?
ends

struct ColorRGBA
        r       GLfloat         ?
        g       GLfloat         ?
        b       GLfloat         ?
        a       GLfloat         ?
ends

WHITE_COLOR Vector3 1.0, 1.0, 1.0
RED_COLOR Vector3 1.0, 0.0, 0.0
GREEN_COLOR Vector3 0.0, 1.0, 0.0
BLUE_COLOR Vector3 0.0, 0.0, 1.0
YELLOW_COLOR Vector3 1.0, 1.0, 0.0
CYAN_COLOR Vector3 0.0, 1.0, 1.0
MAGENTA_COLOR Vector3 1.0, 0.0, 1.0
BLACK_COLOR Vector3 0.0, 0.0, 0.0
GRAY_COLOR Vector3 0.5, 0.5, 0.5
ORANGE_COLOR Vector3 1.0, 0.647, 0.0
PURPLE_COLOR Vector3 0.5, 0.0, 0.5
BROWN_COLOR Vector3 0.6, 0.3, 0.0
