struct Matrix4x4
        m11     dd      ?
        m12     dd      ?
        m13     dd      ?
        m14     dd      ?
        m21     dd      ?
        m22     dd      ?
        m23     dd      ?
        m24     dd      ?
        m31     dd      ?
        m32     dd      ?
        m33     dd      ?
        m34     dd      ?
        m41     dd      ?
        m42     dd      ?
        m43     dd      ?
        m44     dd      ?
ends

view            Matrix4x4           
        model           Matrix4x4         


        scale           Matrix4x4          1.0,0.0,0.0,0.0,\
                                           0.0,1.0,0.0,0.0,\
                                           0.0,0.0,1.0,0.0,\
                                           0.0,0.0,0.0,1.0

        turn            Matrix4x4          

        position        Matrix4x4          1.0,0.0,0.0,0.0,\
                                           0.0,1.0,0.0,0.0,\
                                           0.0,0.0,1.0,0.0,\
                                           0.0,0.0,0.0,1.0

        positionN        Matrix4x4          1.0,0.0,0.0,0.0,\
                                           0.0,1.0,0.0,0.0,\
                                           0.0,0.0,1.0,0.0,\
                                           0.0,0.0,0.0,1.0
        MVP             Matrix4x4

        PV              Matrix4x4

        projection      Matrix4x4  


        tempMatrix      Matrix4x4 
        tempMatrix2      Matrix4x4
        tempMatrix3      Matrix4x4
        tempMatrix4      Matrix4x4        



