PLANE_TRIANGLES_COUNT   =       2
PLANE_VERTICES_COUNT    =       PLANE_TRIANGLES_COUNT * 3
PLANE_INDICES_COUNT    =       PLANE_TRIANGLES_COUNT * 3

planeVertices GLfloat -200.0, -1.0, -200.0,\
                      -200.0, -1.0,  200.0,\
                       200.0, -1.0,  200.0,\
                      -200.0, -1.0, -200.0,\
                       200.0, -1.0,  200.0,\
                       200.0, -1.0, -200.0


