PLANE_TRIANGLES_COUNT   =       2
PLANE_VERTICES_COUNT    =       PLANE_TRIANGLES_COUNT * 3

planeVertices:
                GLfloat -200.0, -1.0, -200.0
                GLfloat -200.0, -1.0,  200.0
                GLfloat  200.0, -1.0,  200.0
                GLfloat -200.0, -1.0, -200.0
                GLfloat  200.0, -1.0,  200.0
                GLfloat  200.0, -1.0, -200.0

planeColors     GLfloat 0.0, 0.655, 0.475,\
                        0.0, 0.655, 0.475,\
                        0.0, 0.655, 0.475,\
                        0.0, 0.655, 0.475,\
                        0.0, 0.655, 0.475,\
                        0.0, 0.655, 0.475