struct Vector3
        x       GLfloat         ?
        y       GLfloat         ?
        z       GLfloat         ?
ends

struct Vector4
        x       GLfloat         ?
        y       GLfloat         ?
        z       GLfloat         ?
        w       GLfloat         ?
ends

struct Vector4i
      x         dd      ?
      y         dd      ?
      z         dd      ?
      w         dd      ?

ends